### ISSUE TITLE
Merge upstream changes

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/blockscout#10]
Merge upstream changes and especially try to include changes to fix the verify bug. 

Suggestion: Merge v2.1.0-beta

**Comment by schmir-at-bb** [comment]
What's the status here? The blockexplorer for tlbc is already running, but it's using the old version.

**Comment by weilbith** [comment]
Last status was that I wait for your setup procedure to check if it works correctly.
Ah and I need to create the issue about removing the night mode feature.

**Comment by schmir-at-bb** [comment]
Where's the code?

**Comment by weilbith** [comment]
I just provided it on the branch called `merge-upstream-changes` for you.
So you intend to test it?

**Comment by weilbith** [comment]
**Status:**
Ralf has deployed the new version at: https://explore.laika.trustlines.foundation
It appears like the old environment variable `$COIN` does not work anymore. Instead of `TLC` all values have the unit `Ether`. We need to figure out how we can change the unit again.

**Comment by weilbith** [comment]
The merge has been already done and tested by functionality. The rest of the appearing issues can be tracked by trustlines-network/project#755.
