### ISSUE TITLE
Optimize Dark Mode colors

### ISSUE THREAD

**Issue by sashseurat** [trustlines-protocol/blockscout#14]
The Dark mode has been introduced by the upstream merges in issue #10 
Currently in the dark mode, there are colors that are either illegible or inconsistent with the brand guidelines.

Find colors that solve the issue.

**Comment by sashseurat** [comment]
I will find colors to quickly solve the issue, while @weilbith  will be the person implementing it.

**Comment by weilbith** [comment]
This includes to enable the night mode button again (see #13)

**Comment by sashseurat** [comment]
Hey, @weilbith, with the colors I sent you, is this issue closed now?

**Comment by weilbith** [comment]
The linked PR contains a link to a current version where the dark mode can be inspected.

**Comment by weilbith** [comment]
PR merged (auto-close failed). -> Done
