### ISSUE TITLE
blocktime wrong on tlbc blockexplorer

### ISSUE THREAD

**Issue by andfletcher** [trustlines-protocol/blockscout#18]
*Describe your issue here.*
The blocktime on https://explore.tlbc.trustlines.foundation/ is 0 milliseconds. 
### Steps to reproduce

Go to https://explore.tlbc.trustlines.foundation/ and look at the blocktime

### Expected behaviour

Should ba about 5 secounds

### Actual behaviour

Shows 0 millisecounds

![image](https://user-images.githubusercontent.com/39694712/69556602-4c290a80-0fa5-11ea-88ee-2ed434110a63.png)

**Comment by schmir-at-bb** [comment]
The server had just been started. You need to wait for some time
