### ISSUE TITLE
wrong transaction number on tlbc blockexplorer

### ISSUE THREAD

**Issue by andfletcher** [trustlines-protocol/blockscout#19]
*Describe your issue here.*

The blockexplorer shows that the number of transactions is 0 but it actually is 1

### Steps to reproduce

Go to https://explore.tlbc.trustlines.foundation/ and view the number of transactions

### Expected behaviour

Should be at least 1

### Actual behaviour

Shows 0
![image](https://user-images.githubusercontent.com/39694712/69556723-901c0f80-0fa5-11ea-8f31-ddf4c61010e3.png)

**Comment by schmir-at-bb** [comment]
The server had just been started. It needs some time to show the correct number (1.5h)
