### ISSUE TITLE
Summary of changes from new blockscout releases

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/blockscout#2]
Find out what changed: https://github.com/poanetwork/blockscout/releases

**Comment by berndbohmeier** [comment]
I summarized some changes we might be interested in. This is of course highly subjective. 

Changes related to contract verification:

1.3.5-beta
- #1560 Verify smart contracts with evm versions
- #1466 - Decoding candidates for unverified contracts

1.3.7-beta 
- #1577 - Add process to fix contract with code

1.3.8-beta
- #1650 - Add petersburg evm version to smart contract verifier

1.3.9-beta
- #1662 - allow specifying number of optimization runs
- #1661 - try to compile smart contract with the latest evm version
- #1665 - Add contract verification RPC endpoint.
- #1712 - do not set contract code from transaction input

1.3.10-beta
- #1790 - fix constructor arguments verification

1.3.13-beta
- #1875 - fix: resolve false positive constructor arguments
- #1881 - fix: store solc versions locally for performance
- #1898 - check if the constructor has arguments before verifying constructor arguments


Other changes we might be interested in:

1.3.5- beta
- #1551 Exact date and time for Transaction details page

1.3.6
- #1586 - Exact timestamp display

1.3.10-beta
#1769 - add timestamp to block overview

1.3.14- beta
- performance fixes

I would try to merge 1.3.14 with ours.

**Comment by schmir-at-bb** [comment]
sure, go on!
