### ISSUE TITLE
Contract verification not working

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/blockscout#27]
We have a problem with contract verification, It seems that blockscout does not use the compile for setting. Even though we set petersburg, the error message reports that we tried to compile for byzantium. 
Check how we can solve this error, maybe merge upstream changes.

**Comment by cducrest** [comment]
We successfully verified the contracts we previously failed to verified. I had deployed the wrong contracts so it is logical the verification was failing. It could be that the bug is still present though, as it was seen from the logs of the blockscout that the wrong evm target version was used.

**Comment by berndbohmeier** [comment]
Did you use default this time or selected the compiler?

**Comment by cducrest** [comment]
I selected the compiler, and used 500 runs

**Comment by weilbith** [comment]
This issue look like it could be closed?

**Comment by cducrest** [comment]
We should / could still investigate why blockscout was using / logging that it was using the wrong target evm version.

**Comment by berndbohmeier** [comment]
Maybe the logging was just wrong. I dont know exactly how to proceed here, so I would close it and if we have an issue with verification again, we can open it again.
