### ISSUE TITLE
Install solidity on the blockscout machine

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/blockscout#5]
Make sure to check how blockscout compiles the contract. It could be that it downloads solidity by itself, or other.

**Comment by schmir-at-bb** [comment]
blockscout automatically downloads solc.js scripts. These have been generated by compiling the solidity source with emscripten. 

I've forced blockscout to download these compiler versions:
```
blockscout@trustlines-blockchain-explorer:~$ find ./blockscout/apps/explorer/priv/solc_compilers/
./blockscout/apps/explorer/priv/solc_compilers/
./blockscout/apps/explorer/priv/solc_compilers/v0.5.9+commit.e560f70d.js
./blockscout/apps/explorer/priv/solc_compilers/v0.4.26+commit.4563c3fc.js
./blockscout/apps/explorer/priv/solc_compilers/v0.5.8+commit.23d335f2.js
./blockscout/apps/explorer/priv/solc_compilers/v0.4.25+commit.59dbf8f1.js
```

We should not manually install those.
